### PR TITLE
refactor: good looking

### PR DESCRIPTION
**Pull request by martiliones**
image

#### Removed

Removed output files for invalid/valid addresses, use /logs instead

#### Changed
`log_level` -> `logLevel`
`node_ADM` -> `nodes`
`skipDublicates` -> `skipDuplicates` 

#### Added
`outputPath` - Output path for list of addresses that bot couldn't send ADM to

#### Changed
- `--mode validate` -> `--validate`
- `--mode airdrop` -> ` `
- Now you need to specify path to config file yourself: `npx adamant-aidrop ./config.jsonc`

## Optimizations

Now the script uses `Set` to check duplicates

### CODE REVIEW

**Comment by martiliones** [comment]
#### Known bug
When the terminal screen's width is too small, besides breaking ascii art, the loading animation is not clearing all the previous lines leaving a mark:
image


Let me know how critical this is

**Comment by adamant-al** [comment]
@martiliones 

- Known bug is not critical
- The `npx adamant-airdrop ./config.json` command doesn't work
- Rename `17:39:43 2024-01-04` output folder to `2024-01-04 17:39:43 validate` and `2024-01-04 17:39:43 airdrop`
- Check output for `node src/index.js --validate ./config.jsonc` — it's wrong
- `Successfully read and validated addresses` ⟶ `Successfully read and validated {number} addresses`
- `1.5369 ADM needed` ⟶ `1.5369 ADM needed: 0.0369 ADM to airdrop and 1.5 ADM for blockchain fees`

**Comment by martiliones** [comment]
@adamant-al why do we need output files for validated addresses? I removed it on purpose because it does the same thing log file does

I just published `adamant-airdrop` package from my own account so you can test `npx`

**Comment by adamant-al** [comment]
> @adamant-al why do we need output files for validated addresses? I removed it on purpose because it does the same thing log file does
> 
> I just published `adamant-airdrop` package from my own account so you can test `npx`

- Give full permissions to GitHub accounts `adamant-al`, `confleux`, `adamantmm` on `adamant-airdrop` in npmjs
- Update Readme. Different instructions for users who use this repo and for users who use npmjs. Fix command output.

E.g., when I use the repo, and run `npm run validate`:

```
> adamant-airdrop@2.0.0 validate
> node src/index.js --validate

Fatal Error:
No configuration file path was provided.
Please provide the path to the config file using the following syntax:
  npx adamant-airdrop ./config.json
```

But `npx adamant-airdrop ./config.json` is not helpful.

When I install `adamant-airdrop` from npmjs and run `cp config.default.jsonc config.jsonc` I get an error.

Consider that this software will use not-technical users.

- Update format `17:39:43 2024-01-04` output folder to `2024-01-04 17:39:43`
- Don't create output folder for validation

**Comment by martiliones** [comment]
- I made the `setup` command to copy default config file.
- Now `npx` command is primary way to use airdrop as it may be complicated to setup the project for "not-technical users" to use `npm` scripts.

image

**Review by adamant-al — APPROVED** [review]

**Comment by adamant-al** [comment]
@confleux 
Check out the refactoring.
Take it as a good example.

**Comment by adamant-al** [comment]
@martiliones 
Check my commits and, if everything is good, merge,
Make a pr to `master` and release in GitHub and npmjs.

**Comment by martiliones** [comment]
```diff
-  logCodeBlock(`cd '${campaignName}'`)
+  logCodeBlock(`cd ${campaignName}`)
```

@adamant-al I think that using quotes here is reasonable because some users might want to have a name that, for example, contains words separated by spaces. In that case, it's not going to work without quotes:

```sh
$ cd campaign name
cd: string not in pwd: campaign
```

**Comment by adamant-al** [comment]
> ```diff
> -  logCodeBlock(`cd '${campaignName}'`)
> +  logCodeBlock(`cd ${campaignName}`)
> ```
> 
> @adamant-al I think that using quotes here is reasonable because some users might want to have a name that, for example, contains words separated by spaces. In that case, it's not going to work without quotes:
> 
> ```shell
> $ cd campaign name
> cd: string not in pwd: askdjsak
> ```

You are right.
Please fix it.

**Pull request merged**
